FROM node:22-alpine

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

ENV NEXT_PUBLIC_API_URL=http://localhost:5000

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
